export type FormData = {
  nama_lengkap: string;
  jenis_kelamin: string;
  tanggal_lahir: string;
  provinsi_domisili: string;
  nomor_handphone: string;
  email: string;
  poltekkes_id: number;
  prodi_id: number;
  tanggal_lulus: string;
  tanggal_str: string;
  status_kerja: string;
  tanggal_kerja: string;
  negara_kerja: string;
  instansi_tempat_kerja: string;
  nama_tempat_kerja: string;
  provinsi_tempat_kerja: string;
  tahun_mulai_kerja: string;
  skema_penempatan_ln: string;
  jabatan: string;
  sk_internasional: string;
  sertifikat_bahasa: string;
  jenjang_pendidikan_ditempuh: string;
  prodi_ditempuh: string;
  kampus_ditempuh: string;
  sosial_media: string;
};
